version: '3.8'
services:
  olspress:
    image: luizeof/dockerpress:latest
    environment:
      - WORDPRESS_URL=${SERVICE_FQDN_OLSPRESS}
      - WORDPRESS_DB_HOST=${WORDPRESS_DB_HOST}
      - WORDPRESS_DB_PORT=${WORDPRESS_DB_PORT}
      - WORDPRESS_DB_USER=${WORDPRESS_DB_USER}
      - WORDPRESS_DB_PASSWORD=${WORDPRESS_DB_PASSWORD}
      - WORDPRESS_DB_NAME=${WORDPRESS_DB_NAME}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
    volumes:
      - wp-data:/var/www/html
    ports:
      - "${HTTP_PORT}:80"
      - "${HTTPS_PORT}:443"
      - "${ADMIN_PORT}:7080"
    entrypoint: ./entrypoint.sh
    networks:
      - coolify
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 10s
      timeout: 5s
      retries: 3
volumes:
  wp-data:
networks:
  coolify:
    external: true
