services:
  olspress:
    image: luizeof/dockerpress:latest
    container_name: dockerpress
    environment:
      - SERVICE_FQDN_OLSPRESS
      - WORDPRESS_DB_HOST=${WORDPRESS_DB_HOST}
      - WORDPRESS_DB_PORT=${WORDPRESS_DB_PORT}
      - WORDPRESS_DB_USER=${WORDPRESS_DB_USER}
      - WORDPRESS_DB_PASSWORD=${WORDPRESS_DB_PASSWORD}
      - WORDPRESS_DB_NAME=${WORDPRESS_DB_NAME}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
    volumes:
      - wp-data:/var/www/html
    networks:
      - coolify
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  coolify:
    external: true
